// Retro
// var _gmapsCustomStyle = [{"elementType": "geometry", "stylers": [{"color": "#ebe3cd"} ] }, {"elementType": "labels.text.fill", "stylers": [{"color": "#523735"} ] }, {"elementType": "labels.text.stroke", "stylers": [{"color": "#f5f1e6"} ] }, {"featureType": "administrative", "elementType": "geometry.stroke", "stylers": [{"color": "#c9b2a6"} ] }, {"featureType": "administrative.land_parcel", "elementType": "geometry.stroke", "stylers": [{"color": "#dcd2be"} ] }, {"featureType": "administrative.land_parcel", "elementType": "labels.text.fill", "stylers": [{"color": "#ae9e90"} ] }, {"featureType": "landscape.natural", "elementType": "geometry", "stylers": [{"color": "#dfd2ae"} ] }, {"featureType": "poi", "elementType": "geometry", "stylers": [{"color": "#dfd2ae"} ] }, {"featureType": "poi", "elementType": "labels.text.fill", "stylers": [{"color": "#93817c"} ] }, {"featureType": "poi.business", "stylers": [{"visibility": "off"} ] }, {"featureType": "poi.park", "elementType": "geometry.fill", "stylers": [{"color": "#a5b076"} ] }, {"featureType": "poi.park", "elementType": "labels.text.fill", "stylers": [{"color": "#447530"} ] }, {"featureType": "road", "elementType": "geometry", "stylers": [{"color": "#f5f1e6"} ] }, {"featureType": "road", "elementType": "labels.icon", "stylers": [{"visibility": "off"} ] }, {"featureType": "road.arterial", "elementType": "geometry", "stylers": [{"color": "#fdfcf8"} ] }, {"featureType": "road.highway", "elementType": "geometry", "stylers": [{"color": "#f8c967"} ] }, {"featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{"color": "#e9bc62"} ] }, {"featureType": "road.highway.controlled_access", "elementType": "geometry", "stylers": [{"color": "#e98d58"} ] }, {"featureType": "road.highway.controlled_access", "elementType": "geometry.stroke", "stylers": [{"color": "#db8555"} ] }, {"featureType": "road.local", "elementType": "labels.text.fill", "stylers": [{"color": "#806b63"} ] }, {"featureType": "transit", "stylers": [{"visibility": "off"} ] }, {"featureType": "transit.line", "elementType": "geometry", "stylers": [{"color": "#dfd2ae"} ] }, {"featureType": "transit.line", "elementType": "labels.text.fill", "stylers": [{"color": "#8f7d77"} ] }, {"featureType": "transit.line", "elementType": "labels.text.stroke", "stylers": [{"color": "#ebe3cd"} ] }, {"featureType": "transit.station", "elementType": "geometry", "stylers": [{"color": "#dfd2ae"} ] }, {"featureType": "water", "elementType": "geometry.fill", "stylers": [{"color": "#b9d3c2"} ] }, {"featureType": "water", "elementType": "labels.text.fill", "stylers": [{"color": "#92998d"} ] } ];

// Flat Pale with labels
// var _gmapsCustomStyle = [{"featureType": "administrative", "elementType": "labels.text.fill", "stylers": [{"color": "#6195a0"} ] }, {"featureType": "administrative.province", "elementType": "geometry.stroke", "stylers": [{"visibility": "off"} ] }, {"featureType": "landscape", "elementType": "geometry", "stylers": [{"visibility": "on"}, {"lightness": "48"}, {"saturation": "-33"} ] }, {"featureType": "landscape.man_made", "elementType": "all", "stylers": [{"lightness": "-3"}, {"gamma": "1.00"} ] }, {"featureType": "landscape.natural.terrain", "elementType": "all", "stylers": [{"visibility": "off"} ] }, {"featureType": "poi", "elementType": "all", "stylers": [{"visibility": "off"} ] }, {"featureType": "poi.park", "elementType": "geometry.fill", "stylers": [{"color": "#bae5ce"}, {"visibility": "on"} ] }, {"featureType": "road", "elementType": "all", "stylers": [{"saturation": -100 }, {"lightness": 45 }, {"visibility": "simplified"} ] }, {"featureType": "road.highway", "elementType": "all", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "road.highway", "elementType": "geometry.fill", "stylers": [{"color": "#fac9a9"}, {"visibility": "simplified"} ] }, {"featureType": "road.highway", "elementType": "labels.text", "stylers": [{"color": "#4e4e4e"} ] }, {"featureType": "road.arterial", "elementType": "labels.text.fill", "stylers": [{"color": "#787878"} ] }, {"featureType": "road.arterial", "elementType": "labels.icon", "stylers": [{"visibility": "off"} ] }, {"featureType": "transit", "elementType": "all", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "transit.station.airport", "elementType": "labels.icon", "stylers": [{"hue": "#0a00ff"}, {"saturation": "-77"}, {"gamma": "0.57"}, {"lightness": "0"} ] }, {"featureType": "transit.station.rail", "elementType": "labels.text.fill", "stylers": [{"color": "#43321e"} ] }, {"featureType": "transit.station.rail", "elementType": "labels.icon", "stylers": [{"hue": "#ff6c00"}, {"lightness": "4"}, {"gamma": "0.75"}, {"saturation": "-68"} ] }, {"featureType": "water", "elementType": "all", "stylers": [{"color": "#eaf6f8"}, {"visibility": "on"} ] }, {"featureType": "water", "elementType": "geometry.fill", "stylers": [{"color": "#c7eced"} ] }, {"featureType": "water", "elementType": "labels.text.fill", "stylers": [{"lightness": "-49"}, {"saturation": "-53"}, {"gamma": "0.79"} ] } ];

// Discreet
// var _gmapsCustomStyle = [{"featureType": "administrative", "elementType": "all", "stylers": [{"visibility": "off"} ] }, {"featureType": "administrative", "elementType": "geometry.stroke", "stylers": [{"visibility": "on"} ] }, {"featureType": "administrative", "elementType": "labels", "stylers": [{"visibility": "on"}, {"color": "#716464"}, {"weight": "0.01"} ] }, {"featureType": "administrative.country", "elementType": "labels", "stylers": [{"visibility": "on"} ] }, {"featureType": "landscape", "elementType": "geometry", "stylers": [{"lightness": "37"} ] }, {"featureType": "landscape.natural", "elementType": "geometry", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "landscape.natural.landcover", "elementType": "geometry", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "poi", "elementType": "all", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "poi", "elementType": "geometry.fill", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "poi", "elementType": "geometry.stroke", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "poi", "elementType": "labels.text", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "poi", "elementType": "labels.text.fill", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "poi", "elementType": "labels.text.stroke", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "poi.attraction", "elementType": "geometry", "stylers": [{"visibility": "on"} ] }, {"featureType": "road", "elementType": "all", "stylers": [{"visibility": "on"} ] }, {"featureType": "road.highway", "elementType": "all", "stylers": [{"visibility": "off"} ] }, {"featureType": "road.highway", "elementType": "geometry", "stylers": [{"visibility": "on"} ] }, {"featureType": "road.highway", "elementType": "geometry.fill", "stylers": [{"visibility": "on"} ] }, {"featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{"visibility": "simplified"}, {"color": "#a05519"}, {"saturation": "-13"} ] }, {"featureType": "road.local", "elementType": "all", "stylers": [{"visibility": "on"} ] }, {"featureType": "transit", "elementType": "all", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "transit", "elementType": "geometry", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "transit.station", "elementType": "geometry", "stylers": [{"visibility": "on"} ] }, {"featureType": "water", "elementType": "all", "stylers": [{"visibility": "simplified"}, {"color": "#84afa3"}, {"lightness": 52 } ] }, {"featureType": "water", "elementType": "geometry", "stylers": [{"visibility": "on"} ] }, {"featureType": "water", "elementType": "geometry.fill", "stylers": [{"visibility": "on"} ] } ];

// Event Lighter
// var _gmapsCustomStyle = [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#6195a0"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2f2f2"}]},{"featureType":"landscape","elementType":"geometry.fill","stylers":[{"color":"#ffffff"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"poi.park","elementType":"geometry.fill","stylers":[{"color":"#e6f3d6"},{"visibility":"on"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45},{"visibility":"simplified"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#f4d2c5"},{"visibility":"simplified"}]},{"featureType":"road.highway","elementType":"labels.text","stylers":[{"color":"#4e4e4e"}]},{"featureType":"road.arterial","elementType":"geometry.fill","stylers":[{"color":"#f4f4f4"}]},{"featureType":"road.arterial","elementType":"labels.text.fill","stylers":[{"color":"#787878"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#eaf6f8"},{"visibility":"on"}]},{"featureType":"water","elementType":"geometry.fill","stylers":[{"color":"#eaf6f8"}]}];

// Discreet [without less POIs]
// var _gmapsCustomStyle = [{'featureType': 'all', 'elementType': 'labels', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'all', 'elementType': 'labels.text', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'administrative', 'elementType': 'all', 'stylers': [{'visibility': 'off'} ] }, {'featureType': 'administrative', 'elementType': 'geometry.stroke', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'administrative', 'elementType': 'labels', 'stylers': [{'visibility': 'on'}, {'color': '#716464'}, {'weight': '0.01'} ] }, {'featureType': 'administrative.country', 'elementType': 'labels', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'landscape', 'elementType': 'geometry', 'stylers': [{'lightness': '37'} ] }, {'featureType': 'landscape.natural', 'elementType': 'geometry', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'landscape.natural.landcover', 'elementType': 'geometry', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'poi', 'elementType': 'all', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'poi.attraction', 'elementType': 'all', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'poi.business', 'elementType': 'all', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'road', 'elementType': 'all', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'road.highway', 'elementType': 'all', 'stylers': [{'visibility': 'off'} ] }, {'featureType': 'road.highway', 'elementType': 'geometry', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'road.highway', 'elementType': 'geometry.fill', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'road.highway', 'elementType': 'geometry.stroke', 'stylers': [{'visibility': 'simplified'}, {'color': '#a05519'}, {'saturation': '-13'} ] }, {'featureType': 'road.local', 'elementType': 'all', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'transit', 'elementType': 'all', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'transit', 'elementType': 'geometry', 'stylers': [{'visibility': 'simplified'} ] }, {'featureType': 'transit.station', 'elementType': 'geometry', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'transit.station.bus', 'elementType': 'all', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'water', 'elementType': 'all', 'stylers': [{'visibility': 'simplified'}, {'color': '#84afa3'}, {'lightness': 52 } ] }, {'featureType': 'water', 'elementType': 'geometry', 'stylers': [{'visibility': 'on'} ] }, {'featureType': 'water', 'elementType': 'geometry.fill', 'stylers': [{'visibility': 'on'} ] } ];

// Discreet v2
window._gmapsCustomStyle = [
  {"featureType": "all", "elementType": "labels.text", "stylers": [{"visibility": "simplified"}, {"lightness": "36"} ] },
  {"featureType": "administrative", "elementType": "all", "stylers": [{"visibility": "off"} ] },
  {"featureType": "administrative", "elementType": "labels", "stylers": [{"visibility": "on"},
  {"color": "#716464"},
  {"weight": "0.01"} ] },
  {"featureType": "landscape", "elementType": "geometry", "stylers": [{"lightness": "37"},
  {"visibility": "on"} ] },
  {"featureType": "landscape.natural", "elementType": "geometry", "stylers": [{"visibility": "simplified"} ] },
  {"featureType": "poi", "elementType": "all", "stylers": [{"visibility": "on"} ] },
  {"featureType": "poi", "elementType": "labels", "stylers": [{"visibility": "off"} ] },
  {"featureType": "poi.park", "elementType": "geometry.fill", "stylers": [{"saturation": "-4"},
  {"lightness": "35"} ] },
  {"featureType": "road", "elementType": "all", "stylers": [{"visibility": "on"} ] },
  {"featureType": "road.highway", "elementType": "all", "stylers": [{"visibility": "off"} ] },
  {"featureType": "road.highway", "elementType": "geometry", "stylers": [{"visibility": "on"} ] },
  {"featureType": "road.highway", "elementType": "geometry.fill", "stylers": [{"visibility": "on"} ] },
  {"featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{"visibility": "simplified"},
  {"color": "#a05519"},
  {"saturation": "-13"} ] },
  {"featureType": "transit", "elementType": "all", "stylers": [{"visibility": "simplified"} ] },
  {"featureType": "transit", "elementType": "geometry", "stylers": [{"visibility": "simplified"} ] },
  {"featureType": "transit.station", "elementType": "labels", "stylers": [{"visibility": "off"} ] },
  {"featureType": "transit.line", "elementType": "all", "stylers": [{"visibility": "off"} ] },
  {"featureType": "transit.station.bus", "elementType": "all", "stylers": [{"visibility": "on"} ] },
  {"featureType": "water", "elementType": "all", "stylers": [{"visibility": "simplified"},
  {"color": "#84afa3"},
  {"lightness": 52 } ] },
  {"featureType": "water", "elementType": "geometry", "stylers": [{"visibility": "on"} ] },
  {"featureType": "water", "elementType": "geometry.fill", "stylers": [{"lightness": "37"},
  {"saturation": "8"} ] }
];

window._gmapsCustomStyle_bikeLayerOptimized = [{"elementType": "labels.text", "stylers": [{"lightness": "36"}, {"visibility": "simplified"} ] }, {"featureType": "administrative", "stylers": [{"visibility": "off"} ] }, {"featureType": "administrative", "elementType": "labels", "stylers": [{"color": "#716464"}, {"visibility": "on"}, {"weight": "0.01"} ] }, {"featureType": "landscape", "stylers": [{"lightness": 50 } ] }, {"featureType": "landscape", "elementType": "geometry", "stylers": [{"lightness": 35 } ] }, {"featureType": "landscape.natural", "elementType": "geometry", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "poi", "stylers": [{"visibility": "on"} ] }, {"featureType": "poi", "elementType": "labels", "stylers": [{"visibility": "off"} ] }, {"featureType": "poi.park", "elementType": "geometry.fill", "stylers": [{"saturation": "-4"}, {"lightness": "35"} ] }, {"featureType": "road", "stylers": [{"visibility": "on"} ] }, {"featureType": "road.highway", "stylers": [{"visibility": "off"} ] }, {"featureType": "road.highway", "elementType": "geometry", "stylers": [{"visibility": "on"} ] }, {"featureType": "road.highway", "elementType": "geometry.fill", "stylers": [{"visibility": "on"} ] }, {"featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{"color": "#a05519"}, {"saturation": "-13"}, {"visibility": "simplified"} ] }, {"featureType": "road.local", "stylers": [{"lightness": -5 }, {"visibility": "on"} ] }, {"featureType": "transit", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "transit", "elementType": "geometry", "stylers": [{"visibility": "simplified"} ] }, {"featureType": "transit.line", "stylers": [{"visibility": "off"} ] }, {"featureType": "transit.station", "elementType": "labels", "stylers": [{"visibility": "off"} ] }, {"featureType": "transit.station.bus", "stylers": [{"visibility": "on"} ] }, {"featureType": "water", "stylers": [{"color": "#84afa3"}, {"lightness": 52 }, {"visibility": "simplified"} ] }, {"featureType": "water", "elementType": "geometry", "stylers": [{"visibility": "on"} ] }, {"featureType": "water", "elementType": "geometry.fill", "stylers": [{"saturation": "8"}, {"lightness": "37"} ] } ];

// Convert JSON gmaps style to URL version for the Static Maps API
// thanks to: https://stackoverflow.com/questions/19115223/converting-google-maps-styles-array-to-google-static-maps-styles-string#
function convertToStaticStyles(stylesArray) {
  var result = [];
  stylesArray.forEach(function(v, i, a){
    var style='';
    if (v.stylers.length > 0) { // Needs to have a style rule to be valid.
      style += (v.hasOwnProperty('featureType') ? 'feature:' + v.featureType : 'feature:all') + '|';
      style += (v.hasOwnProperty('elementType') ? 'element:' + v.elementType : 'element:all') + '|';
      v.stylers.forEach(function(val, i, a){
        var propertyname = Object.keys(val)[0];
        var propertyval = val[propertyname].toString().replace('#', '0x');
        style += propertyname + ':' + propertyval + '|';
      });
    }
    result.push('style='+encodeURIComponent(style));
  });

  return result.join('&');
}

window._gmapsCustomStyleStaticApi = convertToStaticStyles(_gmapsCustomStyle);